/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BusinessUserService } from "../businessUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BusinessUserCreateInput } from "./BusinessUserCreateInput";
import { BusinessUser } from "./BusinessUser";
import { BusinessUserFindManyArgs } from "./BusinessUserFindManyArgs";
import { BusinessUserWhereUniqueInput } from "./BusinessUserWhereUniqueInput";
import { BusinessUserUpdateInput } from "./BusinessUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BusinessUserControllerBase {
  constructor(
    protected readonly service: BusinessUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BusinessUser })
  @nestAccessControl.UseRoles({
    resource: "BusinessUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBusinessUser(
    @common.Body() data: BusinessUserCreateInput
  ): Promise<BusinessUser> {
    return await this.service.createBusinessUser({
      data: data,
      select: {
        businessName: true,
        city: true,
        createdAt: true,
        email: true,
        id: true,
        itemCatalog: true,
        phoneNumber: true,
        promotionCatalog: true,
        state: true,
        street: true,
        subscriptionPlan: true,
        updatedAt: true,
        vatNumber: true,
        zipCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BusinessUser] })
  @ApiNestedQuery(BusinessUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BusinessUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async businessUsers(@common.Req() request: Request): Promise<BusinessUser[]> {
    const args = plainToClass(BusinessUserFindManyArgs, request.query);
    return this.service.businessUsers({
      ...args,
      select: {
        businessName: true,
        city: true,
        createdAt: true,
        email: true,
        id: true,
        itemCatalog: true,
        phoneNumber: true,
        promotionCatalog: true,
        state: true,
        street: true,
        subscriptionPlan: true,
        updatedAt: true,
        vatNumber: true,
        zipCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BusinessUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async businessUser(
    @common.Param() params: BusinessUserWhereUniqueInput
  ): Promise<BusinessUser | null> {
    const result = await this.service.businessUser({
      where: params,
      select: {
        businessName: true,
        city: true,
        createdAt: true,
        email: true,
        id: true,
        itemCatalog: true,
        phoneNumber: true,
        promotionCatalog: true,
        state: true,
        street: true,
        subscriptionPlan: true,
        updatedAt: true,
        vatNumber: true,
        zipCode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BusinessUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBusinessUser(
    @common.Param() params: BusinessUserWhereUniqueInput,
    @common.Body() data: BusinessUserUpdateInput
  ): Promise<BusinessUser | null> {
    try {
      return await this.service.updateBusinessUser({
        where: params,
        data: data,
        select: {
          businessName: true,
          city: true,
          createdAt: true,
          email: true,
          id: true,
          itemCatalog: true,
          phoneNumber: true,
          promotionCatalog: true,
          state: true,
          street: true,
          subscriptionPlan: true,
          updatedAt: true,
          vatNumber: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BusinessUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BusinessUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBusinessUser(
    @common.Param() params: BusinessUserWhereUniqueInput
  ): Promise<BusinessUser | null> {
    try {
      return await this.service.deleteBusinessUser({
        where: params,
        select: {
          businessName: true,
          city: true,
          createdAt: true,
          email: true,
          id: true,
          itemCatalog: true,
          phoneNumber: true,
          promotionCatalog: true,
          state: true,
          street: true,
          subscriptionPlan: true,
          updatedAt: true,
          vatNumber: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
