/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CustomerUserService } from "../customerUser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CustomerUserCreateInput } from "./CustomerUserCreateInput";
import { CustomerUser } from "./CustomerUser";
import { CustomerUserFindManyArgs } from "./CustomerUserFindManyArgs";
import { CustomerUserWhereUniqueInput } from "./CustomerUserWhereUniqueInput";
import { CustomerUserUpdateInput } from "./CustomerUserUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CustomerUserControllerBase {
  constructor(
    protected readonly service: CustomerUserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CustomerUser })
  @nestAccessControl.UseRoles({
    resource: "CustomerUser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCustomerUser(
    @common.Body() data: CustomerUserCreateInput
  ): Promise<CustomerUser> {
    return await this.service.createCustomerUser({
      data: data,
      select: {
        addresses: true,
        city: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        rewardPoints: true,
        savedCards: true,
        state: true,
        street: true,
        transactionHistory: true,
        updatedAt: true,
        walletBalance: true,
        zipCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CustomerUser] })
  @ApiNestedQuery(CustomerUserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CustomerUser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerUsers(@common.Req() request: Request): Promise<CustomerUser[]> {
    const args = plainToClass(CustomerUserFindManyArgs, request.query);
    return this.service.customerUsers({
      ...args,
      select: {
        addresses: true,
        city: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        rewardPoints: true,
        savedCards: true,
        state: true,
        street: true,
        transactionHistory: true,
        updatedAt: true,
        walletBalance: true,
        zipCode: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CustomerUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerUser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async customerUser(
    @common.Param() params: CustomerUserWhereUniqueInput
  ): Promise<CustomerUser | null> {
    const result = await this.service.customerUser({
      where: params,
      select: {
        addresses: true,
        city: true,
        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        phoneNumber: true,
        rewardPoints: true,
        savedCards: true,
        state: true,
        street: true,
        transactionHistory: true,
        updatedAt: true,
        walletBalance: true,
        zipCode: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CustomerUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerUser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCustomerUser(
    @common.Param() params: CustomerUserWhereUniqueInput,
    @common.Body() data: CustomerUserUpdateInput
  ): Promise<CustomerUser | null> {
    try {
      return await this.service.updateCustomerUser({
        where: params,
        data: data,
        select: {
          addresses: true,
          city: true,
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          rewardPoints: true,
          savedCards: true,
          state: true,
          street: true,
          transactionHistory: true,
          updatedAt: true,
          walletBalance: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CustomerUser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CustomerUser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCustomerUser(
    @common.Param() params: CustomerUserWhereUniqueInput
  ): Promise<CustomerUser | null> {
    try {
      return await this.service.deleteCustomerUser({
        where: params,
        select: {
          addresses: true,
          city: true,
          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          phoneNumber: true,
          rewardPoints: true,
          savedCards: true,
          state: true,
          street: true,
          transactionHistory: true,
          updatedAt: true,
          walletBalance: true,
          zipCode: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
