/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RewardPoints } from "./RewardPoints";
import { RewardPointsCountArgs } from "./RewardPointsCountArgs";
import { RewardPointsFindManyArgs } from "./RewardPointsFindManyArgs";
import { RewardPointsFindUniqueArgs } from "./RewardPointsFindUniqueArgs";
import { DeleteRewardPointsArgs } from "./DeleteRewardPointsArgs";
import { RewardPointsService } from "../rewardPoints.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => RewardPoints)
export class RewardPointsResolverBase {
  constructor(
    protected readonly service: RewardPointsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "RewardPoints",
    action: "read",
    possession: "any",
  })
  async _rewardPointsItemsMeta(
    @graphql.Args() args: RewardPointsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [RewardPoints])
  @nestAccessControl.UseRoles({
    resource: "RewardPoints",
    action: "read",
    possession: "any",
  })
  async rewardPointsItems(
    @graphql.Args() args: RewardPointsFindManyArgs
  ): Promise<RewardPoints[]> {
    return this.service.rewardPointsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => RewardPoints, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "RewardPoints",
    action: "read",
    possession: "own",
  })
  async rewardPoints(
    @graphql.Args() args: RewardPointsFindUniqueArgs
  ): Promise<RewardPoints | null> {
    const result = await this.service.rewardPoints(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RewardPoints)
  @nestAccessControl.UseRoles({
    resource: "RewardPoints",
    action: "delete",
    possession: "any",
  })
  async deleteRewardPoints(
    @graphql.Args() args: DeleteRewardPointsArgs
  ): Promise<RewardPoints | null> {
    try {
      return await this.service.deleteRewardPoints(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
